FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Laravel API Example

Welcome to my example api built with Laravel and Docker dev environment with laradocker!

This RESTful API use the api versioning concept, JWT authentication and CORS enabled by default.

More information about this API: [laravel-api-example project](https://github.com/guissilveira/laravel-api-example) on GitHub.

# Group Authentication

## Authentication Collection [/api/v1/authentication]

### Authenticate a user [POST]

Authenticate an User on API.

+ Request (application/json)

        {
            "email": "The e-mail account",
            "password": "The account password"
        }

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User logged.",
                "data": {
                    "id": 2,
                    "name": "User",
                    "email": "user@email.com",
                    "created_at": {
                        "date": "2017-03-28 20:50:54.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    },
                    "updated_at": {
                        "date": "2017-04-06 14:23:21.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    },
                    "token": "eyJ0eXAiOi..."
                }
            }

+ Request (application/json)

            {
                "email": "Wrong email or password",
                "password": "Wrong email or password"
            }

+ Response 401 (application/json)

    + Body   
    
            {
                "error": true,
                "message": "Invalid credentials."
            }

+ Request (application/json)

+ Response 422 (application/json)

    + Body   
    
            {
                "error": true,
                "message": {
                    "email": [
                        "The email field is required."
                    ],
                    "password": [
                        "The password field is required."
                    ]
                }
            }

### Refresh current token [GET /api/v1/authentication/refresh_token]

Receive new token.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer TOKEN

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "Token refreshed.",
                "data": {
                    "token": "eyJ0eXAiOi..."
                }
            }

+ Request (application/json)

    + Headers
    
            Authorization: Bearer EXPIRED_TOKEN

+ Response 401 (application/json)

    + Body
    
            {
                "error": "token_expired"
            }

+ Request (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "error": "token_not_provided"
            }

### Change current password [POST /api/v1/authentication/change_password]

Change current password

+ Request (application/json)

    + Headers
    
            Authorization: Bearer TOKEN
    
    + Body
    
            {
                "_method": "PUT",
                "current_password": "Current password",
                "password": "New password",
                "password_confirmation": "Password confirmation"
            }

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User password changed.",
                "data": {
                    "id": 2,
                    "name": "Guilherme",
                    "email": "guissilveira@gmail.com",
                    "created_at": {
                        "date": "2017-03-28 20:50:54.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    },
                    "updated_at": {
                        "date": "2017-05-08 21:21:51.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    }
                }
            }

### Recover user password [POST /api/v1/authentication/forgot_password]

Receive new password by email.

+ Request (application/json)

        {
            "email": "The e-mail account",
            "password": "The account password"
        }

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User forgot password instructions sent by email.",
                "data": {
                "id": 2,
                "name": "Guilherme",
                "email": "guissilveira@gmail.com",
                "created_at": {
                    "date": "2017-03-28 20:50:54.000000",
                    "timezone_type": 3,
                    "timezone": "UTC"
                },
                "updated_at": {
                    "date": "2017-05-08 21:13:27.000000",
                    "timezone_type": 3,
                    "timezone": "UTC"
                }
                }
            }

### Logout [POST /api/v1/authentication/logout]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer TOKEN

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User logged out."
            }

# Group Users

## Users Collection [/api/v1/users]

### Get all items [GET]

Get all items without any filter.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer TOKEN

+ Response 200 (application/json)

    + Body   
    
            {
                "data": {
                    "data": [
                        {
                            "id": 1,
                            "name": "Nome",
                            "email": "email",
                            "created_at": {
                                "date": "2017-05-09 13:50:44.000000",
                                "timezone_type": 3,
                                "timezone": "UTC"
                            },
                            "updated_at": {
                                "date": "2017-05-09 13:50:44.000000",
                                "timezone_type": 3,
                                "timezone": "UTC"
                            }
                        }
                    ]
                }
            }

### Get one item [GET /api/v1/users/{user_id}]

Get one item.

+ Parameters

    + user_id (number) - ID of the User
    
+ Request (application/json)

    + Headers
    
            Authorization: Bearer TOKEN

+ Response 200 (application/json)

    + Body   
    
            {
                "data": {
                    "id": 1,
                    "name": "Nome",
                    "email": "email",
                    "created_at": {
                        "date": "2017-05-09 13:50:44.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    },
                    "updated_at": {
                        "date": "2017-05-09 13:50:44.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    }
                }
            }

### Create an user [POST]

Create an user.

+ Request (application/json)

        {
            "name": "The name",
            "email": "The e-mail account",
            "password": "The account password"
        }

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User created.",
                "data": {
                    "id": 3,
                    "name": "Teste",
                    "email": "teste@teste.com",
                    "created_at": {
                        "date": "2017-05-09 14:10:24.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    },
                    "updated_at": {
                        "date": "2017-05-09 14:10:24.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    }
                }
            }

+ Request (application/json)

+ Response 422 (application/json)

    + Body   
    
            {
                "error": true,
                "message": {
                    "name": [
                        "The name field is required."
                    ],
                    "email": [
                        "The email field is required."
                    ],
                    "password": [
                        "The password field is required."
                    ]
                }
            }

### Edit an user [POST /api/v1/users/{user_id}]

Edit an user.

+ Parameters

    + user_id (number) - ID of the User

+ Request (application/json)

        {
            "name": "The name",
            "email": "The e-mail account",
            "password": "The account password",
            "_method": "PUT"
        }

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User updated.",
                "data": {
                    "id": 3,
                    "name": "Teste",
                    "email": "teste@teste.com",
                    "created_at": {
                        "date": "2017-05-09 14:10:24.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    },
                    "updated_at": {
                        "date": "2017-05-09 14:10:24.000000",
                        "timezone_type": 3,
                        "timezone": "UTC"
                    }
                }
            }

### Delete an user [POST /api/v1/users/{user_id}]

Edit an user.

+ Parameters

    + user_id (number) - ID of the User

+ Request (application/json)

        {
            "_method": "DELETE"
        }

+ Response 200 (application/json)

    + Body   
    
            {
                "message": "User deleted.",
                "deleted": true
            }